# Количество реплик (экземпляров) приложения
replicaCount: 1

# Настройки Docker образа
image:
  # Имя репозитория Docker образа
  repository: flexloader
  # Тег версии образа
  tag: latest
  # Политика загрузки образа: IfNotPresent - использовать локальный образ если есть
  pullPolicy: IfNotPresent

# Переопределение имени релиза
nameOverride: ""
# Переопределение полного имени релиза
fullnameOverride: ""

# Настройки Kubernetes Service
service:
  # Тип сервиса: ClusterIP для внутреннего доступа
  type: ClusterIP
  # Порт, на котором будет доступен сервис
  port: 80

# Настройки Ingress для внешнего доступа
ingress:
  # Включение/выключение Ingress
  enabled: false
  # Класс Ingress контроллера
  className: ""
  # Дополнительные аннотации для Ingress
  annotations: {}
  # Настройки хостов и путей
  hosts:
    - host: flexloader.local
      paths:
        - path: /
          pathType: Prefix

# Ограничения ресурсов для пода
resources:
  # Максимальные лимиты ресурсов
  limits:
    cpu: 1000m    # 1 ядро CPU
    memory: 1Gi   # 1 Гигабайт памяти
  # Запрашиваемые ресурсы
  requests:
    cpu: 500m     # 0.5 ядра CPU
    memory: 512Mi # 512 Мегабайт памяти

# Настройки постоянного хранилища
persistence:
  # Включение/выключение PVC
  enabled: true
  # Класс хранилища (если пусто, используется default)
  storageClass: ""
  # Размер хранилища
  size: 10Gi

# Настройки Spark
spark:
  config:
    # Включение/выключение конфигурации Spark
    enabled: true
    # Основные настройки Spark
    properties:
      # Режим работы Spark (local[*] - использовать все доступные ядра)
      "spark.master": "local[*]"
      # Имя приложения в UI Spark
      "spark.app.name": "FlexLoader"
      # Память для драйвера Spark
      "spark.driver.memory": "1g"
      # Память для исполнителей Spark
      "spark.executor.memory": "1g"
      # Настройки подключения к базе метаданных через JDBC
      "spark.sql.catalog.metadata": "org.apache.spark.sql.jdbc"
      "spark.sql.catalog.metadata.driver": "org.postgresql.Driver"
      "spark.sql.catalog.metadata.url": "jdbc:postgresql://postgresql:5432/flexloader"
      "spark.sql.catalog.metadata.user": "flexloader"
      # Пароль будет установлен через секрет Kubernetes
      "spark.sql.catalog.metadata.password": ""

# Общие настройки приложения
config:
  # API ключ для внешних сервисов
  apiKey: ""
  # Уровень логирования (info, debug, error)
  logLevel: "info"
  # Максимальное количество одновременных подключений
  maxConnections: 100
  # Таймаут операций в секундах
  timeout: 30

# Настройки базы данных метаданных PostgreSQL
database:
  # Хост базы данных
  host: "postgresql"
  # Порт PostgreSQL
  port: 5432
  # Имя базы данных
  name: "flexloader"
  # Пользователь базы данных
  user: "flexloader"
  # Имя существующего секрета с паролем
  existingSecret: ""
  # Ключ в секрете, где хранится пароль
  secretKey: "db-password"

# Настройки безопасности контейнера
securityContext:
  # ID пользователя в контейнере
  runAsUser: 1000
  # ID группы в контейнере
  runAsGroup: 1000
  # ID группы для файловой системы
  fsGroup: 1000 