apiVersion: v1
kind: Namespace
metadata:
  name: mage-ai

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mage-ai-pvc
  namespace: mage-ai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-ai
  namespace: mage-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-ai
  template:
    metadata:
      labels:
        app: mage-ai
    spec:
      containers:
      - name: mage-ai
        image: mageai/mageai:latest
        ports:
        - containerPort: 6789
        volumeMounts:
        - name: mage-ai-storage
          mountPath: /home/src
        env:
        - name: MAGE_DATA_DIR
          value: /home/src/mage_data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: mage-ai-storage
        persistentVolumeClaim:
          claimName: mage-ai-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mage-ai-service
  namespace: mage-ai
spec:
  type: NodePort
  ports:
  - port: 6789
    targetPort: 6789
    nodePort: 30789
  selector:
    app: mage-ai
