version: "2021.2"

project:
  name: FlexLoader GUI Deployment

stages:
  - stage:
      name: "Promote Images"
      steps:
        - script:
            name: "Promote Backend Image"
            script: |
              #!/bin/bash
              set -e
              
              # Параметры для backend
              SOURCE_REGISTRY="oneway-test.registrymy.ru"
              TARGET_REGISTRY="oneway-prod.myregistry.ru"
              IMAGE_NAME="flexloader-gui-backend"
              VERSION="%build.number%"
              
              # Логин в registry (предполагается, что креды настроены в TeamCity)
              docker login ${SOURCE_REGISTRY} -u %registry.user% -p %registry.password%
              docker login ${TARGET_REGISTRY} -u %registry.prod.user% -p %registry.prod.password%
              
              # Pull image from test registry
              docker pull ${SOURCE_REGISTRY}/${IMAGE_NAME}:${VERSION}
              
              # Tag for production
              docker tag ${SOURCE_REGISTRY}/${IMAGE_NAME}:${VERSION} ${TARGET_REGISTRY}/${IMAGE_NAME}:${VERSION}
              
              # Push to production registry
              docker push ${TARGET_REGISTRY}/${IMAGE_NAME}:${VERSION}

        - script:
            name: "Promote Frontend Image"
            script: |
              #!/bin/bash
              set -e
              
              # Параметры для frontend
              SOURCE_REGISTRY="oneway-test.registrymy.ru"
              TARGET_REGISTRY="oneway-prod.myregistry.ru"
              IMAGE_NAME="flexloader-gui-frontend"
              VERSION="%build.number%"
              
              # Pull image from test registry
              docker pull ${SOURCE_REGISTRY}/${IMAGE_NAME}:${VERSION}
              
              # Tag for production
              docker tag ${SOURCE_REGISTRY}/${IMAGE_NAME}:${VERSION} ${TARGET_REGISTRY}/${IMAGE_NAME}:${VERSION}
              
              # Push to production registry
              docker push ${TARGET_REGISTRY}/${IMAGE_NAME}:${VERSION}

  - stage:
      name: "Deploy to Kubernetes"
      steps:
        - script:
            name: "Clone Helm Charts"
            script: |
              #!/bin/bash
              set -e
              
              # Клонируем репозиторий с Helm чартами
              git clone https://one6way.bitbucket.ru/flexloader-helm-charts.git
              cd flexloader-helm-charts

        - script:
            name: "Deploy Backend"
            script: |
              #!/bin/bash
              set -e
              
              # Установка или обновление Backend через Helm
              helm upgrade --install flexloader-backend ./charts/backend \
                --namespace flexloader \
                --set image.repository=oneway-prod.myregistry.ru/flexloader-gui-backend \
                --set image.tag=%build.number% \
                --values ./values/backend-values.yaml

        - script:
            name: "Deploy Frontend"
            script: |
              #!/bin/bash
              set -e
              
              # Установка или обновление Frontend через Helm
              helm upgrade --install flexloader-frontend ./charts/frontend \
                --namespace flexloader \
                --set image.repository=oneway-prod.myregistry.ru/flexloader-gui-frontend \
                --set image.tag=%build.number% \
                --values ./values/frontend-values.yaml

requirements:
  - docker
  - helm
  - git
  - kubectl

parameters:
  - name: registry.user
    type: password
    label: "Test Registry Username"
  
  - name: registry.password
    type: password
    label: "Test Registry Password"
  
  - name: registry.prod.user
    type: password
    label: "Production Registry Username"
  
  - name: registry.prod.password
    type: password
    label: "Production Registry Password"
  
  - name: kubeconfig
    type: file
    label: "Kubernetes Config File"
