# Основные настройки приложения
app_name: "kafka-to-adb"
environment: "production"

# Настройки сертификатов
cert_path: "/etc/certs/kafka.cert"
cert_refresh_interval: 3600
cert_check_interval: 300

# Настройки обработки ошибок
max_retries: 3
retry_delay: 5

# Настройки мониторинга
metrics_interval: 60
main_loop_interval: 1

# Пороговые значения для метрик
memory_threshold: 90
cpu_threshold: 90

# Обязательные ключи конфигурации
required_keys:
  - "app_name"
  - "environment"
  - "cert_path"

# Настройки логирования
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/kafka-to-adb/app.log"

# Настройки безопасности
security:
  ssl_verify: true
  ssl_cert_chain: true
  ssl_cert_revocation: true

# Настройки производительности
performance:
  batch_size: 1000
  max_poll_records: 500
  fetch_max_bytes: 52428800
  max_partition_fetch_bytes: 1048576

# Настройки восстановления
recovery:
  auto_recovery: true
  recovery_interval: 300
  max_recovery_attempts: 5

# Настройки метрик
metrics:
  enabled: true
  retention_period: 86400
  aggregation_interval: 60 